server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.daomeidan.userService.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS